###
GET http://0.0.0.0:3000/api/jokes/random


###
POST http://0.0.0.0:3000/api/jokes
Content-Type: application/json

{"joke":  "Chuck Norris is the only man to ever defeat a brick wall in a game of tennis."}

###
GET http://0.0.0.0:3000/api/jokes
